In [1]:
import numpy as np

# 1. Create a 1D NumPy array with integers from 1 to 20.
# The np.arange() function creates an array with a sequence of numbers.
# The second argument is exclusive, so we use 21 to include 20.
array = np.arange(1, 21)
print("Original 1D array:")
print(array)
print("-" * 30)

# a. Calculate the sum, mean, median, and standard deviation.

# Calculate the sum of all elements in the array.
array_sum = np.sum(array)

# Calculate the mean (average) of the elements.
array_mean = np.mean(array)

# Calculate the median of the elements.
array_median = np.median(array)

# Calculate the standard deviation of the elements.
array_std = np.std(array)

# Print the calculated statistics.
print("Calculated Statistics:")
print(f"Sum: {array_sum}")
print(f"Mean: {array_mean}")
print(f"Median: {array_median}")
print(f"Standard Deviation: {array_std}")
print("-" * 30)

Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
------------------------------
Calculated Statistics:
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
------------------------------


In [3]:
 # b. Find the indices of elements greater than 10 in the array.
# The np.where() function returns the indices where the condition is True.
# The result is a tuple, so we take the first element to get the array of indices.
indices = np.where(array > 10)

# Print the indices and the corresponding elements.
print("Indices of elements greater than 10:")
print(indices[0]) # Print the array of indices
print("Elements at these indices:")
print(array[indices]) # Print the elements themselves

Indices of elements greater than 10:
[10 11 12 13 14 15 16 17 18 19]
Elements at these indices:
[11 12 13 14 15 16 17 18 19 20]


In [5]:
# 2. Create a 2D NumPy array of shape 4x4 with integers from 1 to 16.
# We first create a 1D array with np.arange(1, 17) and then reshape it.
array_2d = np.arange(1, 17).reshape(4, 4)

# a. Print the array.
print("2D Array (4x4):")
print(array_2d)
print("-" * 30)

# b. Find the transpose of the array.
array_2d_transpose = array_2d.T
print("Transpose of the 2D Array:")
print(array_2d_transpose)
print("-" * 30)

# Axis 1 refers to rows (horizontal).
row_sums = np.sum(array_2d, axis=1)

# Axis 0 refers to columns (vertical).
column_sums = np.sum(array_2d, axis=0)

print("Row-wise sums:")
print(row_sums)
print("-" * 30)
print("Column-wise sums:")
print(column_sums)


2D Array (4x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
------------------------------
Transpose of the 2D Array:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
------------------------------
Row-wise sums:
[10 26 42 58]
------------------------------
Column-wise sums:
[28 32 36 40]


In [6]:
 #Create two 3x3 arrays filled with random integers between 1 and 20.
# np.random.randint(low, high, size) generates an array of random integers.
array_a = np.random.randint(1, 21, size=(3, 3))
array_b = np.random.randint(1, 21, size=(3, 3))

print("Array A (random 3x3):")
print(array_a)
print("-" * 30)
print("Array B (random 3x3):")
print(array_b)
print("=" * 30)

# a. Perform element-wise addition, subtraction, and multiplication.

addition_result = array_a + array_b
subtraction_result = array_a - array_b
multiplication_result = array_a * array_b

print("Element-wise Addition:")
print(addition_result)
print("-" * 30)

print("Element-wise Subtraction:")
print(subtraction_result)
print("-" * 30)

print("Element-wise Multiplication:")
print(multiplication_result)
print("=" * 30)

# b. Compute the dot product of the two arrays.
# The np.dot() function or the @ operator can be used.
dot_product = np.dot(array_a, array_b)

print("Dot Product of Array A and Array B:")
print(dot_product)


Array A (random 3x3):
[[20  8 12]
 [ 2 17 17]
 [16  9  3]]
------------------------------
Array B (random 3x3):
[[10 13 10]
 [13 14  1]
 [14 14  6]]
Element-wise Addition:
[[30 21 22]
 [15 31 18]
 [30 23  9]]
------------------------------
Element-wise Subtraction:
[[ 10  -5   2]
 [-11   3  16]
 [  2  -5  -3]]
------------------------------
Element-wise Multiplication:
[[200 104 120]
 [ 26 238  17]
 [224 126  18]]
Dot Product of Array A and Array B:
[[472 540 280]
 [479 502 139]
 [319 376 187]]


In [7]:
 #4. Reshaping and Slicing Arrays.
# Create a 1D array of size 12.
array_1d_12 = np.arange(1, 13)
print("1D Array of size 12:")
print(array_1d_12)
print("-" * 30)

# Reshape the 1D array into a 3x4 2D array.
reshaped_array = array_1d_12.reshape(3, 4)
print("Reshaped 2D Array (3x4):")
print(reshaped_array)
print("-" * 30)

# Slice the first two rows and last two columns.
sliced_array = reshaped_array[0:2, 2:4]
print("Sliced Array (first two rows and last two columns):")
print(sliced_array)


1D Array of size 12:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
------------------------------
Reshaped 2D Array (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
------------------------------
Sliced Array (first two rows and last two columns):
[[3 4]
 [7 8]]
